const passwordHash = "$2y$10$EvtdxjaWB1y5QhzLGdYGfOsJBo88aXwd3gu6RVPICZn4mSjiWggYu";

const shops = [
  {
    _id: "shop-stationery-kothrud",
    name: "Pooja Kulkarni",
    email: "paperpoint@localmarket.dev",
    passwordHash,
    shopName: "Paper Point Stationery",
    shopLocation: "Kothrud, Pune",
    latitude: 18.5074,
    longitude: 73.8077,
  },
  {
    _id: "shop-bookhouse-deccan",
    name: "Rohan Patil",
    email: "bookhouse@localmarket.dev",
    passwordHash,
    shopName: "Book House Deccan",
    shopLocation: "Deccan Gymkhana, Pune",
    latitude: 18.5162,
    longitude: 73.8417,
  },
  {
    _id: "shop-greenbasket-baner",
    name: "Imran Shaikh",
    email: "greenbasket@localmarket.dev",
    passwordHash,
    shopName: "Green Basket Veg Market",
    shopLocation: "Baner, Pune",
    latitude: 18.559,
    longitude: 73.7868,
  },
  {
    _id: "shop-fruitcart-aundh",
    name: "Meera Kale",
    email: "fruitcart@localmarket.dev",
    passwordHash,
    shopName: "Fresh Fruit Cart",
    shopLocation: "Aundh, Pune",
    latitude: 18.5591,
    longitude: 73.8078,
  },
  {
    _id: "shop-dairyline-wakad",
    name: "Nikhil Jagtap",
    email: "dairyline@localmarket.dev",
    passwordHash,
    shopName: "Dairy Line",
    shopLocation: "Wakad, Pune",
    latitude: 18.5975,
    longitude: 73.7637,
  },
  {
    _id: "shop-bakery-kp",
    name: "Neha Joshi",
    email: "crumbsquare@localmarket.dev",
    passwordHash,
    shopName: "Crumb Square Bakery",
    shopLocation: "Koregaon Park, Pune",
    latitude: 18.5362,
    longitude: 73.8945,
  },
  {
    _id: "shop-spiceroute-jmroad",
    name: "Aarav Sharma",
    email: "spiceroute@localmarket.dev",
    passwordHash,
    shopName: "Spice Route Kitchen",
    shopLocation: "JM Road, Pune",
    latitude: 18.5207,
    longitude: 73.8567,
  },
  {
    _id: "shop-pharma-hinjewadi",
    name: "Sneha Deshmukh",
    email: "careplus@localmarket.dev",
    passwordHash,
    shopName: "Care Plus Pharmacy",
    shopLocation: "Hinjewadi Phase 1, Pune",
    latitude: 18.5912,
    longitude: 73.7389,
  },
];

const products = [
  {
    _id: "prod-notebook-a4",
    name: "A4 Spiral Notebook",
    price: 85,
    originalPrice: 110,
    currency: "INR",
    description: "200-page ruled notebook for school and office use.",
    category: "Stationery",
    type: "notebook",
    attributes: { pages: 200, size: "A4", ruled: true },
    images: ["https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-stationery-kothrud",
  },
  {
    _id: "prod-gel-pen-pack",
    name: "Blue Gel Pen Pack",
    price: 60,
    originalPrice: 75,
    currency: "INR",
    description: "Pack of 10 smooth-writing gel pens.",
    category: "Stationery",
    type: "pen",
    attributes: { inkColor: "blue", quantity: 10 },
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-stationery-kothrud",
  },
  {
    _id: "prod-highlighter-set",
    name: "Pastel Highlighter Set",
    price: 149,
    originalPrice: 189,
    currency: "INR",
    description: "Soft-tone highlighters for note-taking and planners.",
    category: "Stationery",
    type: "highlighter",
    attributes: { colors: 6, finish: "pastel" },
    images: ["https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-stationery-kothrud",
  },
  {
    _id: "prod-math-set",
    name: "Geometry Box",
    price: 120,
    originalPrice: 145,
    currency: "INR",
    description: "Compass, divider, ruler, protractor, and more in one metal box.",
    category: "Stationery",
    type: "geometry-set",
    attributes: { studentUse: true },
    images: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-stationery-kothrud",
  },
  {
    _id: "prod-book-atomic-habits",
    name: "Atomic Habits",
    price: 499,
    originalPrice: 699,
    currency: "INR",
    description: "Popular self-improvement paperback by James Clear.",
    category: "Books",
    type: "paperback",
    attributes: { genre: "self-help", language: "English" },
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-bookhouse-deccan",
  },
  {
    _id: "prod-book-harry-potter",
    name: "Harry Potter and the Philosopher's Stone",
    price: 399,
    originalPrice: 499,
    currency: "INR",
    description: "Fantasy paperback for young readers and collectors.",
    category: "Books",
    type: "novel",
    attributes: { genre: "fantasy", language: "English" },
    images: ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-bookhouse-deccan",
  },
  {
    _id: "prod-book-rich-dad",
    name: "Rich Dad Poor Dad",
    price: 349,
    originalPrice: 450,
    currency: "INR",
    description: "Personal finance classic in paperback.",
    category: "Books",
    type: "paperback",
    attributes: { genre: "finance", language: "English" },
    images: ["https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-bookhouse-deccan",
  },
  {
    _id: "prod-book-ikigai",
    name: "Ikigai",
    price: 320,
    originalPrice: 399,
    currency: "INR",
    description: "Lifestyle and purpose guide with a compact format.",
    category: "Books",
    type: "paperback",
    attributes: { genre: "wellness", language: "English" },
    images: ["https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-bookhouse-deccan",
  },
  {
    _id: "prod-tomato-organic",
    name: "Organic Tomatoes",
    price: 55,
    originalPrice: 65,
    currency: "INR",
    description: "Fresh farm tomatoes sold by the kilogram.",
    category: "Vegetables",
    type: "produce",
    attributes: { unit: "kg", organic: true },
    images: ["https://images.unsplash.com/photo-1546470427-e5e6d2b6d1a4?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-greenbasket-baner",
  },
  {
    _id: "prod-potato-fresh",
    name: "Fresh Potatoes",
    price: 40,
    originalPrice: 48,
    currency: "INR",
    description: "Washed potatoes for daily cooking.",
    category: "Vegetables",
    type: "produce",
    attributes: { unit: "kg", variety: "jyoti" },
    images: ["https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-greenbasket-baner",
  },
  {
    _id: "prod-onion-red",
    name: "Red Onions",
    price: 38,
    originalPrice: 46,
    currency: "INR",
    description: "Sharp and fresh onions from local farms.",
    category: "Vegetables",
    type: "produce",
    attributes: { unit: "kg" },
    images: ["https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-greenbasket-baner",
  },
  {
    _id: "prod-capsicum-green",
    name: "Green Capsicum",
    price: 72,
    originalPrice: 90,
    currency: "INR",
    description: "Crisp capsicum ideal for stir fry and salads.",
    category: "Vegetables",
    type: "produce",
    attributes: { unit: "kg" },
    images: ["https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-greenbasket-baner",
  },
  {
    _id: "prod-banana-robusta",
    name: "Robusta Bananas",
    price: 68,
    originalPrice: 80,
    currency: "INR",
    description: "Sweet ripe bananas sold by the dozen.",
    category: "Fruits",
    type: "fruit",
    attributes: { unit: "dozen" },
    images: ["https://images.unsplash.com/photo-1574226516831-e1dff420e37f?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-fruitcart-aundh",
  },
  {
    _id: "prod-apple-shimla",
    name: "Shimla Apples",
    price: 180,
    originalPrice: 220,
    currency: "INR",
    description: "Premium apples with crisp texture.",
    category: "Fruits",
    type: "fruit",
    attributes: { unit: "kg", grade: "premium" },
    images: ["https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-fruitcart-aundh",
  },
  {
    _id: "prod-mango-alphonso",
    name: "Alphonso Mangoes",
    price: 420,
    originalPrice: 480,
    currency: "INR",
    description: "Seasonal premium mango box.",
    category: "Fruits",
    type: "fruit",
    attributes: { unit: "dozen", seasonal: true },
    images: ["https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-fruitcart-aundh",
  },
  {
    _id: "prod-orange-nagpur",
    name: "Nagpur Oranges",
    price: 140,
    originalPrice: 170,
    currency: "INR",
    description: "Juicy oranges with balanced sweetness.",
    category: "Fruits",
    type: "fruit",
    attributes: { unit: "kg" },
    images: ["https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-fruitcart-aundh",
  },
  {
    _id: "prod-milk-toned",
    name: "Toned Milk 1L",
    price: 62,
    originalPrice: 68,
    currency: "INR",
    description: "Fresh packet milk delivered every morning.",
    category: "Dairy",
    type: "milk",
    attributes: { volume: "1L" },
    images: ["https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-dairyline-wakad",
  },
  {
    _id: "prod-curd-cup",
    name: "Fresh Curd Cup",
    price: 35,
    originalPrice: 40,
    currency: "INR",
    description: "Homestyle curd in a sealed cup.",
    category: "Dairy",
    type: "curd",
    attributes: { weight: "400g" },
    images: ["https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-dairyline-wakad",
  },
  {
    _id: "prod-paneer-block",
    name: "Paneer Block",
    price: 95,
    originalPrice: 110,
    currency: "INR",
    description: "Soft paneer made from fresh milk.",
    category: "Dairy",
    type: "paneer",
    attributes: { weight: "200g", vegetarian: true },
    images: ["https://images.unsplash.com/photo-1631452180539-96aca7d48617?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-dairyline-wakad",
  },
  {
    _id: "prod-butter-unsalted",
    name: "Unsalted Butter",
    price: 58,
    originalPrice: 65,
    currency: "INR",
    description: "Creamy unsalted butter for breakfast and cooking.",
    category: "Dairy",
    type: "butter",
    attributes: { weight: "100g" },
    images: ["https://images.unsplash.com/photo-1589985270958-3494bbd7f4c1?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-dairyline-wakad",
  },
  {
    _id: "prod-croissant-butter",
    name: "Butter Croissant",
    price: 89,
    originalPrice: 99,
    currency: "INR",
    description: "Flaky layered croissant baked fresh each morning.",
    category: "Bakery",
    type: "baked-good",
    attributes: { freshlyBaked: true },
    images: ["https://images.unsplash.com/photo-1555507036-ab794f4afe5b?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-bakery-kp",
  },
  {
    _id: "prod-sourdough-loaf",
    name: "Sourdough Loaf",
    price: 220,
    originalPrice: 260,
    currency: "INR",
    description: "Crusty artisan sourdough loaf.",
    category: "Bakery",
    type: "bread",
    attributes: { weight: "500g" },
    images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-bakery-kp",
  },
  {
    _id: "prod-cold-coffee",
    name: "Cold Coffee",
    price: 120,
    originalPrice: 140,
    currency: "INR",
    description: "Chilled coffee with vanilla cream foam.",
    category: "Beverage",
    type: "drink",
    attributes: { servedCold: true, size: "regular" },
    images: ["https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-bakery-kp",
  },
  {
    _id: "prod-red-velvet-slice",
    name: "Red Velvet Slice",
    price: 145,
    originalPrice: 170,
    currency: "INR",
    description: "Cream cheese frosted red velvet pastry slice.",
    category: "Bakery",
    type: "pastry",
    attributes: { eggless: false },
    images: ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-bakery-kp",
  },
  {
    _id: "prod-margherita-pizza",
    name: "Margherita Pizza",
    price: 249,
    originalPrice: 299,
    currency: "INR",
    description: "Stone-baked pizza with tomato, mozzarella, and basil.",
    category: "Pizza",
    type: "food",
    attributes: { size: "medium", vegetarian: true },
    images: ["https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-spiceroute-jmroad",
  },
  {
    _id: "prod-veg-burger",
    name: "Veg Burger",
    price: 159,
    originalPrice: 189,
    currency: "INR",
    description: "Crisp veg patty with house sauce and lettuce.",
    category: "Burger",
    type: "food",
    attributes: { portion: "single", vegetarian: true },
    images: ["https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-spiceroute-jmroad",
  },
  {
    _id: "prod-paneer-tikka-wrap",
    name: "Paneer Tikka Wrap",
    price: 199,
    originalPrice: 229,
    currency: "INR",
    description: "Paneer tikka wrap with mint chutney and onions.",
    category: "Wraps",
    type: "food",
    attributes: { spiceLevel: "medium", vegetarian: true },
    images: ["https://images.unsplash.com/photo-1530469912745-a215c6b256ea?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-spiceroute-jmroad",
  },
  {
    _id: "prod-masala-fries",
    name: "Masala Fries",
    price: 129,
    originalPrice: 149,
    currency: "INR",
    description: "Crispy fries tossed with Indian masala seasoning.",
    category: "Snacks",
    type: "food",
    attributes: { spiceLevel: "medium" },
    images: ["https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-spiceroute-jmroad",
  },
  {
    _id: "prod-paracetamol-pack",
    name: "Paracetamol 650",
    price: 32,
    originalPrice: 36,
    currency: "INR",
    description: "Tablet strip for fever and pain relief.",
    category: "Pharmacy",
    type: "medicine",
    attributes: { dosage: "650mg", prescription: false },
    images: ["https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-pharma-hinjewadi",
  },
  {
    _id: "prod-vitamin-c",
    name: "Vitamin C Tablets",
    price: 180,
    originalPrice: 220,
    currency: "INR",
    description: "Immunity support supplement tablets.",
    category: "Pharmacy",
    type: "supplement",
    attributes: { tablets: 60, prescription: false },
    images: ["https://images.unsplash.com/photo-1582719471384-894fbb16e074?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-pharma-hinjewadi",
  },
  {
    _id: "prod-bandage-pack",
    name: "Bandage Pack",
    price: 45,
    originalPrice: 55,
    currency: "INR",
    description: "First-aid adhesive bandages in assorted sizes.",
    category: "Pharmacy",
    type: "first-aid",
    attributes: { pieces: 20 },
    images: ["https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-pharma-hinjewadi",
  },
  {
    _id: "prod-hand-sanitizer",
    name: "Hand Sanitizer",
    price: 99,
    originalPrice: 120,
    currency: "INR",
    description: "Pocket-sized sanitizer bottle.",
    category: "Pharmacy",
    type: "hygiene",
    attributes: { volume: "100ml", alcohol: "70%" },
    images: ["https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=900&q=80"],
    userId: "shop-pharma-hinjewadi",
  },
];

db.users.deleteMany({});
db.products.deleteMany({});
db.users.insertMany(shops);
db.products.insertMany(products);

printjson({
  usersInserted: db.users.countDocuments(),
  productsInserted: db.products.countDocuments(),
});
